export const NO_BOOTCAMP_NAME = "You need to enter a bootcamp name"
export const NO_BOOTCAMP_TOTAL_CREDITS = "You need to enter total credits"
export const NO_ALLOWCATION_CREDITS_DATA = "You need to add one or more fields to allowcate total Credits"
export const MISSING_FIELD_INFO = "You forget to add some fields information"
export const MISSING_FIELD_NAME = "Please enter a field name"
export const MISSING_SMALL_FIELD = "You need to add one or more child fields"
export const NOT_CORRECT_CREDITS = "You are not allowcated credits right"
export const NOT_EQUAL_CREDITS = "Total subject credits are not equal to total Field credits"
export const NOT_EQUAL_OR_HIGER_CREDITS = "Total subject credits are not equal or higher than total Field credits"
export const MISSING_SUBJECT_IN_SEMESTER = "You need to add one or more subjects to this semester"
export const SUBJECT_STILL_REMAIN = "These are still some Compulsory Subjects need to push into semester"


export const VIEW_NOT_EQUAL_TOTAL_CREDITS = "You are not allowcated all credits"
export const VIEW_NOT_EQUAL_CREDITS_IN_SUBJECTLIST = "Total subject credits are not equal to allowcated credits"